# Generated by Django 3.2.4 on 2021-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
