# Generated by Django 3.2.4 on 2021-06-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210620_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name': 'Дополниетельное поле продукта', 'verbose_name_plural': 'Дополниетельные поля продукта'},
        ),
    ]
